### ISSUE TITLE
Old alloy dependencies (EIP-712 nested struct hashing bug)

### ISSUE THREAD

**Issue by edburmai** [OffchainLabs/stylus-sdk-rs#93] opened 2023-12-22 15:55 UTC
Currently, `stylus-sdk-rs` depends on `alloy-primitives` and `alloy-sol-types` version 0.3.1. This version contains a known [EIP-712](https://eips.ethereum.org/EIPS/eip-712) nested struct hashing bug (https://github.com/alloy-rs/core/issues/257).

Example: `eip712_signing_hash` for `Mail` produces an incorrect hash.
```
sol! {
      struct Person {
          string name;
          address wallet;
      }

      struct Mail {
          Person from;
          Person to;
          string contents;
      }
  }
```

**Comment by rory-ocl** [comment] 2024-06-21 19:18
Duplicate of #125

**Closed by rory-ocl** 2024-06-21 19:18 UTC
