### ISSUE TITLE
bug: Solidity type aliases defined inside `sol!` macro cannot be used as Solidity struct members

### ISSUE THREAD

**Issue by target-san** [OffchainLabs/stylus-sdk-rs#81] opened 2023-11-09 11:23 UTC
Issue:
```
sol! {
    type Foo as uint32;
    struct Bar {
        Foo foo;
    }
}
```
will fail to compile

Cause: `alloy-sol-macro` transitive dependency v0.3.1 vs 0.3.2, former one generating such `SolStruct` impl that it requires all fields to be `SolStruct`s themselves, while latter one doesn't require it.
Yet, v0.3.2 cannot be picked by resolver. It requires `syn-solidity = "0.3.2"` while latest `stylus-proc` 0.4.1 has strict requirement `syn-solidity = "=0.3.1"`

~Proposed solution: relax requirement in `stylus-proc` to `syn-solidity = "0.3.1"`~

EDIT: Seems `syn-solidity` was pinned due to breaking changes. While requirement can't be simply relaxed back, I'll leave this bug here.

**Comment by rory-ocl** [comment] 2024-06-21 19:18
Duplicate of #125

**Closed by rory-ocl** 2024-06-21 19:18 UTC
